on:
  push:
    branches: main
    paths:
      - ".github/workflows/update_upstreams.yml"
      - "steamcmd/**"
  workflow_dispatch: {}
  schedule: [ cron: "0 0 * * 1" ]

jobs:
  job-90-linux-steamcmd:
    runs-on: ubuntu-latest
    steps:
      - name: preparing system
        env: { DEBIAN_FRONTEND: noninteractive }
        run: |
          sudo apt update --assume-yes
          sudo apt install --assume-yes apt-utils
          sudo apt install --assume-yes debconf
          sudo apt full-upgrade --assume-yes
          sudo apt install --assume-yes git rsync podman
      - name: cloning main branch
        uses: actions/checkout@v4
        with: { ref: main }
      - name: generating steamcmd podman image
        run: |
          mkdir -p .tmp/build_context.podman
          tar --create --directory steamcmd/app_update.podman . | tar --extract --directory .tmp/build_context.podman
          mkdir --parents .tmp/build_context.podman/files/usr/local/bin
          cp steamcmd/app_update.py .tmp/build_context.podman/files/usr/local/bin/entry_point.py
          podman build --tag app_update.steamcmd.local .tmp/build_context.podman
      - name: downloading upstream via steamcmd podman image
        run: |
          mkdir --parents .tmp/download
          podman run --rm --volume "$(pwd)/.tmp/download":/root/.local/share/Steam/steamapps/common/Half-Life -- app_update.steamcmd.local /usr/games/steamcmd 90 -beta beta
      - name: cloning storage branch
        uses: actions/checkout@v4
        with:
          ref: linux.90.steamcmd.upstreams.storage
          path: .tmp/storage
      - name: appying changes
        working-directory: .tmp/storage
        run: |
          rsync --delete --archive '${{github.workspace}}/.tmp/download/' contents
          test -n "`git status --porcelain contents`" || exit 0
          git add --all contents
          git config --local user.email "noreply@example.com"
          git config --local user.name "autoupdate workflow"
          git commit --message "autoupdate from upstream via steamcmd"
      - name: uploading changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: linux.90.steamcmd.upstreams.storage
          directory: .tmp/storage
          github_token: "${{github.token}}"
  job-90-windows-steamcmd:
    runs-on: windows-latest
    steps:
      - name: cloning main branch
        uses: actions/checkout@v4
        with: { ref: main }
      - name: downloading upstream via steamcmd
        run: |
          New-Item -ItemType "directory" -Path ".tmp\download"
          Copy-Item -Path "${{github.workspace}}\steamcmd\steamcmd.exe" -Destination ".tmp\download"
          python3 steamcmd\app_update.py .tmp\download\steamcmd.exe 90 -beta beta
      - name: cloning storage branch
        uses: actions/checkout@v4
        with:
          ref: windows.90.steamcmd.upstreams.storage
          path: .tmp/storage
      - name: appying changes
        working-directory: .tmp/storage
        run: |
          git config --local core.autocrlf false
          git reset --hard HEAD
          if (Test-Path -Path "contents") { Remove-Item -Recurse -Force -Path "contents"; }
          Copy-Item -Recurse -Path "${{github.workspace}}\.tmp\download\steamapps\common\Half-Life" -Destination "contents"
          $_response = & git status --porcelain contents; if ([string]::IsNullOrEmpty($_response)) { exit 0; }
          git add --all contents
          git config --local user.email "noreply@example.com"
          git config --local user.name "autoupdate workflow"
          git commit --message "autoupdate from upstream via steamcmd"
      - name: uploading changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: windows.90.steamcmd.upstreams.storage
          directory: .tmp/storage
          github_token: "${{github.token}}"
  job-agmod-github:
    runs-on: ubuntu-latest
    steps:
      - name: preparing system
        env: { DEBIAN_FRONTEND: noninteractive }
        run: |
          sudo apt update --assume-yes
          sudo apt install --assume-yes apt-utils
          sudo apt install --assume-yes debconf
          sudo apt full-upgrade --assume-yes
          sudo apt install --assume-yes git curl
      - name: downloading upstream archive from github
        run: |
          mkdir --parents .tmp/download
          curl --output .tmp/download/upstream.tar.gz --location https://github.com/martinwebrant/agmod/raw/master/redist/Full/Linux/ag_66.tar.gz
      - name: cloning storage branch
        uses: actions/checkout@v4
        with:
          ref: agmod.github.upstreams.storage
          path: .tmp/storage
      - name: appying changes
        working-directory: .tmp/storage
        run: |
          rm --force --recursive contents
          mkdir --parents contents/ag
          tar --extract --file '${{github.workspace}}/.tmp/download/upstream.tar.gz' --directory contents/ ag/
          test -n "`git status --porcelain contents`" || exit 0
          git add --all contents
          git config --local user.email "noreply@example.com"
          git config --local user.name "autoupdate workflow"
          git commit --message "autoupdate from upstream on github"
      - name: uploading changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          branch: agmod.github.upstreams.storage
          directory: .tmp/storage
          github_token: "${{github.token}}"
